/**
 * SpecCompiler — deterministic EngineChartSpec + SemanticModel → parameterized,
 * tenant-scoped ClickHouse SQL. NO LLM here: the LLM only produced the spec; the
 * SQL is generated by code so there is no hallucination surface. See
 * docs/TARGET_ARCHITECTURE.md §4⑤.
 *
 * Correctness is enforced by construction:
 *   - ratio measures ⇒ sum(num)/nullIf(sum(den),0)      (never avg-of-ratios)
 *   - semi_additive  ⇒ argMax(col, timeCol)             (never sum-of-stock)
 *   - every query is scoped by tenant_id + org_id PARAMS (never interpolation)
 */

import type {
  EngineChartSpec,
  MeasureExpr,
  SemanticMeasure,
  SemanticModel,
} from './semantic-model.types';

export type ValueFormat = 'currency' | 'percent' | 'number';

/** A frontend-ready series descriptor (matches DashboardPreview's display.series). */
export interface EngineSeries {
  key: string;
  role: 'bar' | 'line';
  axis: 'left' | 'right';
  format: ValueFormat;
}

/** The display hints a widget carries — drives axis/role/formatting, never math. */
export interface EngineDisplay {
  chartType: string;
  valueFormat: ValueFormat;
  series?: EngineSeries[];
  secondaryAxisFormat?: ValueFormat;
  secondaryLabel?: string;
  /** Human axis TITLES so the chart reads on its own: what the x/y axes mean. */
  xAxisLabel?: string;
  yAxisLabel?: string;
  highlightNames?: string[];
  highlightTopN?: number;
  labelSeries?: string;
  highlightNegative?: boolean;
  /** 100%-stacked contribution chart: EVERY series is a percentage share, whatever
   * its name — the renderer must format all series as percent, never infer $ from a
   * series name like "Voice Revenue". */
  normalized?: boolean;
}

/** The tenant isolation predicate — parameters, never string interpolation. */
export const SCOPE_WHERE =
  'tenant_id = {tenantId:String} AND org_id IN ({externalOrgIds:Array(String)})';

export interface CompileContext {
  analyticsDb: string;
  tenantId: string;
  externalOrgIds: string[];
  /** Hard row cap; always applied. */
  maxRows?: number;
}

/** Collision-proof column name used by the analytic/headline query. ClickHouse
 * expands SELECT aliases globally, so `sum(revenue) AS revenue` can become the
 * illegal nested expression `sum(sum(revenue))`. Public rows are normalized
 * back to semantic measure keys by ChartEngineService after execution. */
export function compiledMeasureColumn(index: number): string {
  return `__measure_${index}`;
}

export type CompileResult =
  | { ok: true; sql: string; params: Record<string, unknown> }
  | { ok: false; reason: string };

function distributionColumn(measure: SemanticMeasure): string | null {
  switch (measure.expr.kind) {
    case 'sum':
    case 'mean':
    case 'last_value':
    case 'max':
      return measure.expr.column;
    default:
      return null;
  }
}

function ident(name: string): string {
  // ClickHouse identifiers we emit come from the introspected schema, never user
  // text, but we still hard-reject anything non-identifier-shaped as defense.
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    throw new Error(`unsafe identifier: ${JSON.stringify(name)}`);
  }
  return name;
}

/** Compile a MeasureExpr to a SQL aggregate expression. The correctness core. */
function compileMeasureExpr(expr: MeasureExpr): string {
  switch (expr.kind) {
    case 'sum':
      return `sum(${ident(expr.column)})`;
    case 'count_distinct':
      return `uniqExact(${ident(expr.column)})`;
    case 'max':
      return `max(${ident(expr.column)})`;
    case 'last_value':
      // Point-in-time level: the value at the latest time within the group.
      return `argMax(${ident(expr.column)}, ${ident(expr.orderBy)})`;
    case 'ratio_of_sums':
      // The ONLY way a percentage/rate is ever produced.
      return `sum(${ident(expr.numerator)}) / nullIf(sum(${ident(expr.denominator)}), 0)`;
    case 'mean':
      // Row-level average/duration. Weighted (sum/sum) when the cube carries a
      // pre-summed value + weight; else a plain avg over the grouped rows. The
      // value is already in its natural unit (percent-points/days) — NOT scaled.
      return expr.weight
        ? `sum(${ident(expr.column)}) / nullIf(sum(${ident(expr.weight)}), 0)`
        : `avg(${ident(expr.column)})`;
    default: {
      const _exhaustive: never = expr;
      throw new Error(`unhandled measure expr: ${JSON.stringify(_exhaustive)}`);
    }
  }
}

function timeGrainExpr(
  grain: NonNullable<EngineChartSpec['timeGrain']>,
  col: string,
): string {
  const c = ident(col);
  switch (grain) {
    case 'day':
      return `toDate(${c})`;
    case 'month':
      return `toStartOfMonth(${c})`;
    case 'quarter':
      return `toStartOfQuarter(${c})`;
    case 'year':
      return `toStartOfYear(${c})`;
  }
}

/**
 * A HUMAN axis label for a time bucket, computed in SQL so the chart carries
 * "Jan 2025" / "Q1 2025" / "2025" instead of a raw "2025-01-01". The bucket is
 * still grouped/ordered by its underlying date expression (see below), so the
 * pretty label never breaks chronological order. The frontend's date parser
 * recognizes these shapes, so time-scope filtering keeps working.
 */
function timeLabelExpr(
  grain: NonNullable<EngineChartSpec['timeGrain']>,
  bucketExpr: string,
): string {
  switch (grain) {
    case 'day':
      // "5 Jan 2025" — no zero-padding, reads naturally.
      return `concat(toString(toDayOfMonth(${bucketExpr})), ' ', formatDateTime(${bucketExpr}, '%b %Y'))`;
    case 'month':
      return `formatDateTime(${bucketExpr}, '%b %Y')`;
    case 'quarter':
      return `concat('Q', toString(toQuarter(${bucketExpr})), ' ', toString(toYear(${bucketExpr})))`;
    case 'year':
      return `toString(toYear(${bucketExpr}))`;
  }
}

/** Double-quoted ClickHouse column alias, escaping embedded quotes. Labels come
 * from the introspected model (never user text) but we escape defensively. */
function quoteAlias(label: string): string {
  return `"${label.replace(/"/g, '""')}"`;
}

function stringLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

/** The value expression for a measure, ratio-scaled to percent-points (×100) so
 * the UI's percent formatter renders 33.7 → "33.7%". The single source of truth
 * for how a measure becomes a numeric column. */
function measureValueExpr(m: SemanticMeasure): string {
  return m.expr.kind === 'ratio_of_sums'
    ? `round(100 * (${compileMeasureExpr(m.expr)}), 4)`
    : compileMeasureExpr(m.expr);
}

/** Conditional counterpart used for aligned period comparisons. */
function measureValueExprIf(m: SemanticMeasure, condition: string): string {
  switch (m.expr.kind) {
    case 'sum':
      return `sumIf(${ident(m.expr.column)}, ${condition})`;
    case 'count_distinct':
      return `uniqExactIf(${ident(m.expr.column)}, ${condition})`;
    case 'max':
      return `maxIf(${ident(m.expr.column)}, ${condition})`;
    case 'last_value':
      return `argMaxIf(${ident(m.expr.column)}, ${ident(m.expr.orderBy)}, ${condition})`;
    case 'ratio_of_sums':
      return `round(100 * sumIf(${ident(m.expr.numerator)}, ${condition}) / nullIf(sumIf(${ident(m.expr.denominator)}, ${condition}), 0), 4)`;
    case 'mean':
      return m.expr.weight
        ? `sumIf(${ident(m.expr.column)}, ${condition}) / nullIf(sumIf(${ident(m.expr.weight)}, ${condition}), 0)`
        : `avgIf(${ident(m.expr.column)}, ${condition})`;
  }
}

/** Map a measure's unit to the UI value format. */
function unitFormat(unit: string): ValueFormat {
  return unit === '%' ? 'percent' : unit === 'USD' ? 'currency' : 'number';
}

/** A human y-axis title from a measure's unit: the plain unit for money/percent,
 * else the measure's own name (e.g. "Employees") so a count axis still reads. */
function yAxisTitleFor(m: SemanticMeasure): string {
  if (m.unit === 'USD') return 'USD';
  if (m.unit === '%') return 'Percent';
  // Distinct-count measures commonly use a technical *_key column. The key is
  // how the count is computed, not what the reader should see on the axis.
  return m.expr.kind === 'count_distinct'
    ? m.label.replace(/\s+Key$/i, '')
    : m.label;
}

/** Human x-axis title: the dimension's name, or the time grain, or nothing. */
function xAxisTitle(
  spec: EngineChartSpec,
  model: SemanticModel,
): string | undefined {
  if (spec.timeGrain)
    return spec.timeGrain.charAt(0).toUpperCase() + spec.timeGrain.slice(1);
  if (spec.dimensionKey) {
    const dim = model.dimensions.find((d) => d.key === spec.dimensionKey);
    if (dim) return dim.label;
  }
  return undefined;
}

/**
 * Turn a spec + model into frontend display hints: for a single measure, just
 * the value format; for several, a `series[]` that assigns each measure to the
 * left or right axis by UNIT (same unit as the primary → left; a different unit
 * → its own right axis as a line), which is exactly what "add gross margin on
 * another axis" should produce — a dual-axis combo. Pure + unit-testable.
 */
export function buildEngineDisplay(
  spec: EngineChartSpec,
  model: SemanticModel,
): EngineDisplay {
  const allMeasures = spec.measureKeys
    .map((k) => model.measures.find((m) => m.key === k))
    .filter((m): m is SemanticMeasure => !!m);
  const labelMeasure = spec.labelMeasureKey
    ? allMeasures.find((measure) => measure.key === spec.labelMeasureKey)
    : undefined;
  const measures = labelMeasure
    ? allMeasures.filter((measure) => measure.key !== labelMeasure.key)
    : allMeasures;
  // Percentage-contribution charts are always in percent, whatever the measure's
  // native unit — each series is its share of the per-axis total.
  const primaryFmt: ValueFormat = spec.normalize
    ? 'percent'
    : spec.comparison === 'yoy_growth_pct'
      ? 'percent'
      : measures.length
        ? unitFormat(measures[0]!.unit)
        : 'number';
  const normalizedYLabel = spec.normalize ? 'Share of total (%)' : undefined;
  const xAxisLabel = xAxisTitle(spec, model);
  const decorate = (display: EngineDisplay): EngineDisplay => {
    let d = display;
    if (spec.highlightNames?.length)
      d = { ...d, highlightNames: spec.highlightNames };
    if (spec.highlightTopN) d = { ...d, highlightTopN: spec.highlightTopN };
    if (labelMeasure) d = { ...d, labelSeries: labelMeasure.label };
    if (spec.highlightNegative) d = { ...d, highlightNegative: true };
    if (spec.normalize) d = { ...d, normalized: true };
    return d;
  };

  if (spec.comparison === 'previous_year' && measures.length >= 1) {
    return decorate({
      chartType: spec.chartType,
      valueFormat: primaryFmt,
      xAxisLabel: xAxisLabel ?? 'Period',
      yAxisLabel: yAxisTitleFor(measures[0]!),
      series: [
        { key: 'Current Year', role: 'line', axis: 'left', format: primaryFmt },
        {
          key: 'Previous Year',
          role: 'line',
          axis: 'left',
          format: primaryFmt,
        },
      ],
    });
  }

  if (spec.comparison === 'yoy_growth_pct' && measures.length >= 1) {
    return decorate({
      chartType: spec.chartType,
      valueFormat: 'percent',
      xAxisLabel: xAxisLabel ?? 'Period',
      yAxisLabel: 'YoY Growth (%)',
    });
  }

  // KPI/scorecard widgets intentionally mix units in one card grid. Preserve
  // that requested visual instead of converting it to a dual-axis combo.
  if (
    spec.chartType === 'kpi' ||
    spec.chartType === 'radar' ||
    spec.chartType === 'funnel' ||
    spec.chartType === 'sankey'
  ) {
    return decorate({
      chartType: spec.chartType,
      valueFormat: primaryFmt,
      ...(xAxisLabel ? { xAxisLabel } : {}),
      ...(measures[0] ? { yAxisLabel: yAxisTitleFor(measures[0]) } : {}),
    });
  }

  // Point charts encode measures on their numeric axes; differing units are
  // expected and must not coerce the requested scatter/bubble into a combo.
  if (
    (spec.chartType === 'scatter' || spec.chartType === 'bubble') &&
    measures.length >= 2
  ) {
    return decorate({
      chartType: spec.chartType,
      valueFormat: primaryFmt,
      xAxisLabel: measures[0]!.label,
      yAxisLabel: measures[1]!.label,
      secondaryAxisFormat: unitFormat(measures[1]!.unit),
      ...(measures[2] ? { secondaryLabel: measures[2].label } : {}),
    });
  }

  if (measures.length <= 1) {
    return decorate({
      chartType: spec.chartType,
      valueFormat: primaryFmt,
      ...(xAxisLabel ? { xAxisLabel } : {}),
      ...(normalizedYLabel
        ? { yAxisLabel: normalizedYLabel }
        : measures.length
          ? { yAxisLabel: yAxisTitleFor(measures[0]!) }
          : {}),
    });
  }

  const baseRole: 'bar' | 'line' =
    spec.chartType === 'line' || spec.chartType === 'area' ? 'line' : 'bar';
  const primaryAggregation = measures[0]?.expr.kind;
  const series: EngineSeries[] = measures.map((m, i) => {
    const fmt = unitFormat(m.unit);
    // The same display format does not necessarily mean the same numeric scale.
    // A summed dollar total and an average dollar rate (revenue vs billing rate,
    // for example) are different semantic quantities and become unreadable on a
    // shared axis. Keep genuinely comparable aggregations together, but give a
    // differently aggregated measure its own line/right axis.
    const sameScale = fmt === primaryFmt && m.expr.kind === primaryAggregation;
    return {
      key: m.label,
      role: i === 0 || sameScale ? baseRole : 'line',
      axis: i === 0 || sameScale ? 'left' : 'right',
      format: fmt,
    };
  });
  const right = series.find((s) => s.axis === 'right');
  return decorate({
    chartType: right ? 'combo' : spec.chartType,
    valueFormat: primaryFmt,
    series,
    ...(xAxisLabel ? { xAxisLabel } : {}),
    yAxisLabel: yAxisTitleFor(measures[0]!),
    ...(right
      ? { secondaryAxisFormat: right.format, secondaryLabel: right.key }
      : {}),
  });
}

/**
 * Compile a MULTI-series result: `name` + one value column per measure, aliased
 * by the measure's label. This is the shape the dashboard's combo / multi-series
 * renderer expects — deliberately NO `value` column, so the frontend treats each
 * measure column as its own series. Same correctness + scoping as the others.
 * Use when spec.measureKeys.length > 1.
 */
export function compileSeriesSql(
  spec: EngineChartSpec,
  model: SemanticModel,
  ctx: CompileContext,
): CompileResult {
  const measures = spec.measureKeys.map((k) =>
    model.measures.find((m) => m.key === k),
  );
  const missing = spec.measureKeys.filter((_, i) => !measures[i]);
  if (missing.length)
    return { ok: false, reason: `unknown measure(s): ${missing.join(', ')}` };
  const resolved = measures as SemanticMeasure[];
  const table = resolved[0]!.sourceTable;
  if (resolved.some((m) => m.sourceTable !== table))
    return { ok: false, reason: 'cross-table not supported' };

  const primaryDim = spec.dimensionKey
    ? model.dimensions.find((d) => d.key === spec.dimensionKey)
    : undefined;
  const explicitBreakdown = spec.breakdownKey
    ? model.dimensions.find((d) => d.key === spec.breakdownKey)
    : undefined;
  if (spec.dimensionKey && !primaryDim)
    return { ok: false, reason: `unknown dimension: ${spec.dimensionKey}` };
  if (spec.breakdownKey && !explicitBreakdown)
    return {
      ok: false,
      reason: `unknown breakdown dimension: ${spec.breakdownKey}`,
    };
  if ([primaryDim, explicitBreakdown].some((d) => d && d.table !== table)) {
    return { ok: false, reason: 'cross-table not supported' };
  }

  // Multi-dimensional visuals use a generic long-form contract:
  //   name = primary category/time, series = breakdown value, value = aggregate.
  // The frontend pivots this to wide rows for stacked bars/areas and heatmaps.
  // This avoids hardcoding any category values into SQL or application code.
  const implicitTimeBreakdown = !!spec.timeGrain && !!primaryDim;

  if (spec.comparison === 'yoy_growth_pct') {
    if (!spec.timeGrain || !model.time) {
      return { ok: false, reason: 'YoY growth requires a time grain' };
    }
    if (explicitBreakdown) {
      return {
        ok: false,
        reason: 'YoY growth supports one categorical breakdown',
      };
    }
    if (resolved.length !== 1) {
      return { ok: false, reason: 'YoY growth supports one base measure' };
    }

    const measure = resolved[0]!;
    const bucket = timeGrainExpr(spec.timeGrain, model.time.column);
    const periodLabel = timeLabelExpr(spec.timeGrain, 'cur.period');
    const dimensionSelect = primaryDim
      ? `, if(empty(toString(${ident(primaryDim.column)})), 'Unallocated', toString(${ident(primaryDim.column)})) AS series`
      : '';
    const dimensionGroup = primaryDim ? `, ${ident(primaryDim.column)}` : '';
    const dimensionJoin = primaryDim ? ' AND prev.series = cur.series' : '';
    const outerSeries = primaryDim ? ', series' : '';
    const innerSeries = primaryDim ? ', cur.series AS series' : '';
    const seriesOrder = primaryDim ? ', series ASC' : '';
    const sql =
      `WITH base AS (\n` +
      `  SELECT ${bucket} AS period${dimensionSelect}, toFloat64(${measureValueExpr(measure)}) AS amount\n` +
      `  FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
      `  WHERE ${SCOPE_WHERE}\n` +
      `  GROUP BY ${bucket}${dimensionGroup}\n` +
      `)\n` +
      `SELECT name${outerSeries}, value FROM (\n` +
      `  SELECT ${periodLabel} AS name${innerSeries}, ` +
      `round(100 * (cur.amount - prev.amount) / nullIf(abs(prev.amount), 0), 4) AS value, cur.period AS _series_order\n` +
      `  FROM base AS cur\n` +
      `  INNER JOIN base AS prev ON prev.period = addYears(cur.period, -1)${dimensionJoin}\n` +
      `  WHERE abs(prev.amount) > 0.000000000001\n` +
      `)\n` +
      `WHERE isFinite(value)\n` +
      `ORDER BY _series_order ASC${seriesOrder}\n` +
      `LIMIT ${ctx.maxRows ?? 5000}`;
    return {
      ok: true,
      sql,
      params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
    };
  }

  if (spec.comparison === 'previous_year') {
    if (!spec.timeGrain || !model.time)
      return {
        ok: false,
        reason: 'previous-year comparison requires a time grain',
      };
    if (explicitBreakdown)
      return {
        ok: false,
        reason: 'previous-year comparison supports one categorical breakdown',
      };
    const measure = resolved[0]!;
    const timeColumn = ident(model.time.column);
    const latestYear = `(SELECT max(toYear(${timeColumn})) FROM ${ident(ctx.analyticsDb)}.${ident(table)} WHERE ${SCOPE_WHERE})`;
    const currentCondition = `toYear(${timeColumn}) = ${latestYear}`;
    const previousCondition = `toYear(${timeColumn}) = ${latestYear} - 1`;
    const periodOrder =
      spec.timeGrain === 'quarter'
        ? `toQuarter(${timeColumn})`
        : spec.timeGrain === 'year'
          ? `toYear(${timeColumn})`
          : spec.timeGrain === 'day'
            ? `toDayOfYear(${timeColumn})`
            : `toMonth(${timeColumn})`;
    const periodLabel =
      spec.timeGrain === 'quarter'
        ? `concat('Q', toString(toQuarter(${timeColumn})))`
        : spec.timeGrain === 'year'
          ? `'Year'`
          : spec.timeGrain === 'day'
            ? `formatDateTime(${timeColumn}, '%d %b')`
            : `formatDateTime(${timeColumn}, '%b')`;
    const currentValue = measureValueExprIf(measure, currentCondition);
    const previousValue = measureValueExprIf(measure, previousCondition);
    if (primaryDim) {
      const dimColumn = ident(primaryDim.column);
      const base = (label: string, value: string) =>
        `SELECT ${periodLabel} AS name, concat(toString(${dimColumn}), ' — ${label}') AS series, toFloat64(${value}) AS value, ${periodOrder} AS _ord\n` +
        `FROM ${ident(ctx.analyticsDb)}.${ident(table)} WHERE ${SCOPE_WHERE} AND toYear(${timeColumn}) IN (${latestYear}, ${latestYear} - 1)\n` +
        `GROUP BY ${periodOrder}, name, ${dimColumn}\nHAVING abs(ifNull(value, 0)) > 0.000000000001`;
      const sql =
        `SELECT name, series, value FROM (\n${base('Current Year', currentValue)}\nUNION ALL\n${base('Previous Year', previousValue)}\n) ` +
        `ORDER BY _ord ASC, series ASC LIMIT ${ctx.maxRows ?? 5000}`;
      return {
        ok: true,
        sql,
        params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
      };
    }
    if (spec.chartType === 'waterfall') {
      const sql =
        `WITH totals AS (SELECT toFloat64(${currentValue}) AS current_value, toFloat64(${previousValue}) AS previous_value\n` +
        `FROM ${ident(ctx.analyticsDb)}.${ident(table)} WHERE ${SCOPE_WHERE} AND toYear(${timeColumn}) IN (${latestYear}, ${latestYear} - 1))\n` +
        `SELECT name, value, is_total FROM (\n` +
        `SELECT 1 AS ord, 'Previous Year' AS name, previous_value AS value, 1 AS is_total FROM totals\nUNION ALL\n` +
        `SELECT 2 AS ord, 'Change' AS name, current_value - previous_value AS value, 0 AS is_total FROM totals\nUNION ALL\n` +
        `SELECT 3 AS ord, 'Current Year' AS name, current_value AS value, 1 AS is_total FROM totals) ORDER BY ord LIMIT 3`;
      return {
        ok: true,
        sql,
        params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
      };
    }
    const sql =
      `SELECT ${periodLabel} AS name, toFloat64(${currentValue}) AS "Current Year", toFloat64(${previousValue}) AS "Previous Year"\n` +
      `FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
      `WHERE ${SCOPE_WHERE} AND toYear(${timeColumn}) IN (${latestYear}, ${latestYear} - 1)\n` +
      `GROUP BY ${periodOrder}, name\n` +
      `HAVING abs(ifNull("Current Year", 0)) > 0.000000000001 OR abs(ifNull("Previous Year", 0)) > 0.000000000001\n` +
      `ORDER BY ${periodOrder} ASC\nLIMIT ${ctx.maxRows ?? 5000}`;
    return {
      ok: true,
      sql,
      params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
    };
  }

  // Scatter/bubble charts use an explicit x/y/z transport contract. A generic
  // multi-measure row (or the long-form series contract below) would render as
  // a combo or collapse all bubbles to zero. The point name is assembled from
  // whichever categorical/time dimensions the planner selected.
  if (spec.chartType === 'scatter' || spec.chartType === 'bubble') {
    if (resolved.length < 2)
      return {
        ok: false,
        reason: 'point chart requires at least two measures',
      };
    if (spec.timeGrain && !model.time)
      return { ok: false, reason: 'no time column' };
    if (!primaryDim && !explicitBreakdown && !spec.timeGrain) {
      return {
        ok: false,
        reason: 'point chart requires a category or time dimension',
      };
    }

    const groupExprs: string[] = [];
    const nameExprs: string[] = [];
    if (primaryDim) {
      groupExprs.push(ident(primaryDim.column));
      nameExprs.push(`toString(${ident(primaryDim.column)})`);
    }
    if (explicitBreakdown && explicitBreakdown.key !== primaryDim?.key) {
      groupExprs.push(ident(explicitBreakdown.column));
      nameExprs.push(`toString(${ident(explicitBreakdown.column)})`);
    }
    let pointOrderExpr: string;
    if (spec.timeGrain) {
      const bucket = timeGrainExpr(spec.timeGrain, model.time!.column);
      groupExprs.push(bucket);
      nameExprs.push(timeLabelExpr(spec.timeGrain, bucket));
      pointOrderExpr = bucket;
    } else {
      pointOrderExpr = measureValueExpr(resolved[0]!);
    }

    const pointMeasures = resolved.slice(0, 3);
    const aliases = ['x', 'y', 'z'];
    const valueSelect = pointMeasures
      .map(
        (measure, index) =>
          `toFloat64(${measureValueExpr(measure)}) AS ${aliases[index]!}`,
      )
      .join(', ');
    const having = pointMeasures
      .map((_, index) => `abs(ifNull(${aliases[index]!}, 0)) > 0.000000000001`)
      .join(' OR ');
    const maxRows = ctx.maxRows ?? 5000;
    const limit =
      spec.topN && spec.topN > 0 ? Math.min(spec.topN, maxRows) : maxRows;
    const nameExpr =
      nameExprs.length === 1
        ? nameExprs[0]!
        : `concat(${nameExprs.flatMap((expr, index) => (index === 0 ? [expr] : [stringLiteral(' — '), expr])).join(', ')})`;
    const sql =
      `SELECT ${nameExpr} AS name, ${valueSelect}\n` +
      `FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
      `WHERE ${SCOPE_WHERE}\n` +
      `GROUP BY ${groupExprs.join(', ')}\n` +
      `HAVING ${having}\n` +
      `ORDER BY ${pointOrderExpr} ${spec.timeGrain ? 'ASC' : spec.sort === 'asc' ? 'ASC' : 'DESC'}\n` +
      `LIMIT ${limit}`;
    return {
      ok: true,
      sql,
      params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
    };
  }

  if (explicitBreakdown || implicitTimeBreakdown) {
    if (spec.timeGrain && !model.time)
      return { ok: false, reason: 'no time column' };
    const axisExpr = spec.timeGrain
      ? timeLabelExpr(
          spec.timeGrain,
          timeGrainExpr(spec.timeGrain, model.time!.column),
        )
      : `toString(${ident(primaryDim!.column)})`;
    const orderExpr = spec.timeGrain
      ? timeGrainExpr(spec.timeGrain, model.time!.column)
      : `toString(${ident(primaryDim!.column)})`;
    const seriesDim = explicitBreakdown ?? primaryDim!;
    const groupExprs = spec.timeGrain
      ? [
          timeGrainExpr(spec.timeGrain, model.time!.column),
          ident(seriesDim.column),
        ]
      : [ident(primaryDim!.column), ident(seriesDim.column)];
    const maxRows = ctx.maxRows ?? 5000;
    const primaryFormat = unitFormat(resolved[0]!.unit);
    const primaryAggregation = resolved[0]!.expr.kind;
    const parts = resolved.map((m, index) => {
      // A mixed-scale follow-up on a stacked breakdown needs two different
      // granularities: keep the primary measure split into the requested stack,
      // but aggregate overlay measures once per x-axis bucket. Otherwise the
      // chart produces one salary/margin line per grade/category and becomes a
      // misleading tangle. Same-scale component measures remain fully stacked.
      const isOverlay =
        index > 0 &&
        (unitFormat(m.unit) !== primaryFormat ||
          m.expr.kind !== primaryAggregation);
      const seriesExpr = isOverlay
        ? stringLiteral(m.label)
        : resolved.length === 1
          ? `toString(${ident(seriesDim.column)})`
          : `concat(toString(${ident(seriesDim.column)}), ' — ', ${stringLiteral(m.label)})`;
      const measureGroupExprs = isOverlay
        ? spec.timeGrain
          ? [timeGrainExpr(spec.timeGrain, model.time!.column)]
          : [ident(primaryDim!.column)]
        : groupExprs;
      // UNION ALL requires one common numeric type across measures (e.g.
      // uniqExact → UInt64 and avg salary → Float64). Float64 is the dashboard's
      // transport type; the source aggregation semantics remain unchanged.
      const valueExpr = `toFloat64(${measureValueExpr(m)})`;
      return (
        `SELECT ${axisExpr} AS name, ${seriesExpr} AS series, ${valueExpr} AS value, ${orderExpr} AS _series_order\n` +
        `FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
        `WHERE ${SCOPE_WHERE}\n` +
        `GROUP BY ${measureGroupExprs.join(', ')}\n` +
        `HAVING abs(ifNull(value, 0)) > 0.000000000001`
      );
    });
    // Percentage contribution (100%-stacked): each series becomes its share of
    // the per-axis-bucket total. round to 2dp; the display formats it as percent.
    const valueOut = spec.normalize
      ? `round(100 * value / nullIf(sum(value) OVER (PARTITION BY name), 0), 2)`
      : `value`;
    const sql =
      `SELECT name, series, ${valueOut} AS value FROM (\n${parts.join('\nUNION ALL\n')}\n)\n` +
      `ORDER BY _series_order ASC, series ASC\nLIMIT ${maxRows}`;
    return {
      ok: true,
      sql,
      params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
    };
  }

  let nameExpr = `'Total'`;
  let groupBy = '';
  let timeBucket: string | null = null;
  if (spec.dimensionKey) {
    const dim = model.dimensions.find((d) => d.key === spec.dimensionKey);
    if (!dim)
      return { ok: false, reason: `unknown dimension: ${spec.dimensionKey}` };
    if (dim.table !== table)
      return { ok: false, reason: 'cross-table not supported' };
    nameExpr = `toString(${ident(dim.column)})`;
    groupBy = `\nGROUP BY ${ident(dim.column)}`;
  } else if (spec.timeGrain) {
    if (!model.time) return { ok: false, reason: 'no time column' };
    timeBucket = timeGrainExpr(spec.timeGrain, model.time.column);
    nameExpr = timeLabelExpr(spec.timeGrain, timeBucket);
    groupBy = `\nGROUP BY ${timeBucket}`;
  }

  const valueCols = resolved
    .map((m) => `${measureValueExpr(m)} AS ${quoteAlias(m.label)}`)
    .join(', ');
  const having = groupBy
    ? `\nHAVING ${resolved.map((m) => `abs(ifNull(${quoteAlias(m.label)}, 0)) > 0.000000000001`).join(' OR ')}`
    : '';
  const maxRows = ctx.maxRows ?? 5000;
  const limit =
    spec.topN && spec.topN > 0 ? Math.min(spec.topN, maxRows) : maxRows;
  const orderBy = timeBucket
    ? `\nORDER BY ${timeBucket} ASC`
    : `\nORDER BY ${quoteAlias(resolved[0]!.label)} ${spec.sort === 'asc' ? 'ASC' : 'DESC'}`;

  const sql =
    `SELECT ${nameExpr} AS name, ${valueCols}\n` +
    `FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
    `WHERE ${SCOPE_WHERE}` +
    groupBy +
    having +
    orderBy +
    `\nLIMIT ${limit}`;
  return {
    ok: true,
    sql,
    params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
  };
}

/**
 * Compile to a two-column `(name, value)` result — the shape the existing
 * dashboard "dynamic widget" renderer expects. `name` is the dimension (or the
 * time period, or a constant when neither), `value` is the FIRST measure. Same
 * correctness guarantees as compileSpec (ratio→SUM/SUM, stock→argMax, scoped).
 */
export function compileNameValueSql(
  spec: EngineChartSpec,
  model: SemanticModel,
  ctx: CompileContext,
): CompileResult {
  const measure = model.measures.find((m) => m.key === spec.measureKeys[0]);
  if (!measure)
    return { ok: false, reason: `unknown measure: ${spec.measureKeys[0]}` };

  let nameExpr = `'Total'`;
  let groupBy = '';
  // When the axis is time, we keep the underlying date bucket to sort by so the
  // pretty label ("Jan 2025") never falls out of chronological order.
  let timeBucket: string | null = null;
  if (spec.dimensionKey) {
    const dim = model.dimensions.find((d) => d.key === spec.dimensionKey);
    if (!dim)
      return { ok: false, reason: `unknown dimension: ${spec.dimensionKey}` };
    if (dim.table !== measure.sourceTable)
      return { ok: false, reason: 'cross-table not supported' };
    nameExpr = `toString(${ident(dim.column)})`;
    groupBy = `\nGROUP BY ${ident(dim.column)}`;
  } else if (spec.timeGrain) {
    if (!model.time) return { ok: false, reason: 'no time column' };
    timeBucket = timeGrainExpr(spec.timeGrain, model.time.column);
    nameExpr = timeLabelExpr(spec.timeGrain, timeBucket);
    groupBy = `\nGROUP BY ${timeBucket}`;
  }

  // Ratios are stored/derived as a 0..1 fraction; the UI's percent formatter
  // expects percent-points (33.7 → "33.7%"), so scale ratio measures ×100.
  const valueExpr = measureValueExpr(measure);
  const having = groupBy
    ? `\nHAVING abs(ifNull(value, 0)) > 0.000000000001`
    : '';
  const maxRows = ctx.maxRows ?? 5000;
  const limit =
    spec.topN && spec.topN > 0 ? Math.min(spec.topN, maxRows) : maxRows;
  // Time axis: chronological by the underlying date bucket (NOT by the pretty
  // label — "Apr" must not sort before "Jan"). Otherwise: biggest value first.
  const orderBy = timeBucket
    ? `\nORDER BY ${timeBucket} ASC`
    : `\nORDER BY value ${spec.sort === 'asc' ? 'ASC' : 'DESC'}`;

  const sql =
    `SELECT ${nameExpr} AS name, ${valueExpr} AS value\n` +
    `FROM ${ident(ctx.analyticsDb)}.${ident(measure.sourceTable)}\n` +
    `WHERE ${SCOPE_WHERE}` +
    groupBy +
    having +
    orderBy +
    `\nLIMIT ${limit}`;
  return {
    ok: true,
    sql,
    params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
  };
}

/** Compile genuine row-level distributions rather than charting one aggregate
 * as if it were a distribution. The model supplies the column and category;
 * no dataset values or category names are embedded here. */
export function compileDistributionSql(
  spec: EngineChartSpec,
  model: SemanticModel,
  ctx: CompileContext,
): CompileResult {
  const measure = model.measures.find((m) => m.key === spec.measureKeys[0]);
  if (!measure)
    return { ok: false, reason: `unknown measure: ${spec.measureKeys[0]}` };
  const rawColumn = distributionColumn(measure);
  if (!rawColumn)
    return {
      ok: false,
      reason: 'distribution requires a row-level numeric measure',
    };
  const column = ident(rawColumn);
  const dbTable = `${ident(ctx.analyticsDb)}.${ident(measure.sourceTable)}`;
  const params = { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds };

  if (spec.chartType === 'box_plot') {
    const dim = spec.dimensionKey
      ? model.dimensions.find((d) => d.key === spec.dimensionKey)
      : undefined;
    if (spec.dimensionKey && !dim)
      return { ok: false, reason: `unknown dimension: ${spec.dimensionKey}` };
    if (dim && dim.table !== measure.sourceTable)
      return { ok: false, reason: 'cross-table not supported' };
    const name = dim
      ? `if(empty(toString(${ident(dim.column)})), 'Unallocated', toString(${ident(dim.column)}))`
      : `'All records'`;
    const group = dim ? `\nGROUP BY ${ident(dim.column)}` : '';
    const sql =
      `SELECT ${name} AS name, toFloat64(min(${column})) AS min, ` +
      `toFloat64(quantileExact(0.25)(${column})) AS q1, toFloat64(quantileExact(0.5)(${column})) AS median, ` +
      `toFloat64(quantileExact(0.75)(${column})) AS q3, toFloat64(max(${column})) AS max, count() AS employee_count\n` +
      `FROM ${dbTable}\nWHERE ${SCOPE_WHERE} AND isFinite(toFloat64(${column}))${group}\n` +
      `ORDER BY (max - min) DESC\nLIMIT ${Math.min(spec.topN ?? 50, ctx.maxRows ?? 5000)}`;
    return { ok: true, sql, params };
  }

  const binCount = 12;
  const sql =
    `WITH bounds AS (SELECT min(toFloat64(${column})) AS lo, max(toFloat64(${column})) AS hi FROM ${dbTable} ` +
    `WHERE ${SCOPE_WHERE} AND isFinite(toFloat64(${column}))),\n` +
    `binned AS (SELECT greatest(0, least(${binCount - 1}, toInt32(floor((toFloat64(${column}) - lo) / nullIf(hi - lo, 0) * ${binCount})))) AS bin, lo, hi ` +
    `FROM ${dbTable} CROSS JOIN bounds WHERE ${SCOPE_WHERE} AND isFinite(toFloat64(${column})))\n` +
    `SELECT concat(toString(round(lo + bin * (hi - lo) / ${binCount}, 2)), '–', toString(round(lo + (bin + 1) * (hi - lo) / ${binCount}, 2))) AS name, count() AS value\n` +
    `FROM binned GROUP BY bin, lo, hi ORDER BY bin ASC\nLIMIT ${binCount}`;
  return { ok: true, sql, params };
}

export function compileSpec(
  spec: EngineChartSpec,
  model: SemanticModel,
  ctx: CompileContext,
): CompileResult {
  if (!spec.measureKeys.length)
    return { ok: false, reason: 'no measures in spec' };

  const measures = spec.measureKeys.map((k) =>
    model.measures.find((m) => m.key === k),
  );
  const missing = spec.measureKeys.filter((_, i) => !measures[i]);
  if (missing.length)
    return { ok: false, reason: `unknown measure(s): ${missing.join(', ')}` };
  const resolved = measures as NonNullable<(typeof measures)[number]>[];

  // v1 supports single-fact-table queries; cross-table joins are a later phase.
  const tables = new Set(resolved.map((m) => m.sourceTable));
  let dimension: SemanticModel['dimensions'][number] | undefined;
  if (spec.dimensionKey) {
    dimension = model.dimensions.find((d) => d.key === spec.dimensionKey);
    if (!dimension)
      return { ok: false, reason: `unknown dimension: ${spec.dimensionKey}` };
    tables.add(dimension.table);
  }
  let breakdown: SemanticModel['dimensions'][number] | undefined;
  if (spec.breakdownKey) {
    breakdown = model.dimensions.find((d) => d.key === spec.breakdownKey);
    if (!breakdown)
      return {
        ok: false,
        reason: `unknown breakdown dimension: ${spec.breakdownKey}`,
      };
    tables.add(breakdown.table);
  }
  if (spec.timeGrain && model.time) tables.add(model.time.table);
  if (tables.size > 1) {
    return {
      ok: false,
      reason: `cross-table query not supported in v1 (tables: ${[...tables].join(', ')})`,
    };
  }
  const table = resolved[0]!.sourceTable;

  const selectParts: string[] = [];
  const groupParts: string[] = [];

  if (dimension) {
    selectParts.push(`${ident(dimension.column)} AS \`${dimension.key}\``);
    groupParts.push(ident(dimension.column));
  }
  if (breakdown) {
    selectParts.push(`${ident(breakdown.column)} AS \`${breakdown.key}\``);
    groupParts.push(ident(breakdown.column));
  }
  if (spec.timeGrain) {
    if (!model.time)
      return {
        ok: false,
        reason: 'spec requests a time grain but model has no time column',
      };
    const t = timeGrainExpr(spec.timeGrain, model.time.column);
    selectParts.push(`${t} AS period`);
    groupParts.push(t);
  }

  for (const [index, m] of resolved.entries()) {
    selectParts.push(
      `${compileMeasureExpr(m.expr)} AS \`${compiledMeasureColumn(index)}\``,
    );
  }

  const maxRows = ctx.maxRows ?? 5000;
  const limit =
    spec.topN && spec.topN > 0 ? Math.min(spec.topN, maxRows) : maxRows;

  let orderBy = '';
  if (spec.topN && resolved[0]) {
    const dir = spec.sort === 'asc' ? 'ASC' : 'DESC';
    orderBy = `\nORDER BY \`${compiledMeasureColumn(0)}\` ${dir}`;
  } else if (spec.timeGrain) {
    orderBy = `\nORDER BY period ASC`;
  }

  const groupBy = groupParts.length
    ? `\nGROUP BY ${groupParts.join(', ')}`
    : '';
  const having = groupParts.length
    ? `\nHAVING ${resolved.map((_, index) => `abs(ifNull(\`${compiledMeasureColumn(index)}\`, 0)) > 0.000000000001`).join(' OR ')}`
    : '';

  const sql =
    `SELECT ${selectParts.join(', ')}\n` +
    `FROM ${ident(ctx.analyticsDb)}.${ident(table)}\n` +
    `WHERE ${SCOPE_WHERE}` +
    groupBy +
    having +
    orderBy +
    `\nLIMIT ${limit}`;

  return {
    ok: true,
    sql,
    params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
  };
}

/**
 * Scoped SQL that INDEPENDENTLY re-sums a ratio measure's numerator and
 * denominator as two raw columns (no grouping, no HAVING, no scaling). The
 * executor compares the charted ratio against SUM(num)/SUM(den) from this query
 * — the live tripwire that keeps the avg-of-ratios class of bug from silently
 * reappearing (docs/TARGET_ARCHITECTURE.md §9, guardrail #5). Returns a refusal
 * only when handed a non-ratio measure (a caller bug), never for data reasons.
 */
export function compileRatioComponentsTotal(
  measure: SemanticMeasure,
  ctx: CompileContext,
): CompileResult {
  if (measure.expr.kind !== 'ratio_of_sums') {
    return { ok: false, reason: `not a ratio measure: ${measure.key}` };
  }
  const { numerator, denominator } = measure.expr;
  const sql =
    `SELECT sum(${ident(numerator)}) AS \`num\`, sum(${ident(denominator)}) AS \`den\`\n` +
    `FROM ${ident(ctx.analyticsDb)}.${ident(measure.sourceTable)}\n` +
    `WHERE ${SCOPE_WHERE}`;
  return {
    ok: true,
    sql,
    params: { tenantId: ctx.tenantId, externalOrgIds: ctx.externalOrgIds },
  };
}
